// Generates src/generated/operations.ts from docs/04-api/openapi.yaml (ADR-014 §2):
// the list of money operations (`x-money: true`), which must carry an Idempotency-Key (ADR-003 §6).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const here = dirname(fileURLToPath(import.meta.url));
const contractPath = resolve(here, '../../../docs/04-api/openapi.yaml');
const outDir = resolve(here, '../src/generated');
mkdirSync(outDir, { recursive: true });

const contract = parse(readFileSync(contractPath, 'utf8'));
const METHODS = ['get', 'put', 'post', 'patch', 'delete'];
const money = [];
for (const [path, item] of Object.entries(contract.paths)) {
  for (const method of METHODS) {
    const op = item[method];
    if (op?.['x-money'] === true)
      money.push({ method: method.toUpperCase(), path, id: op.operationId });
  }
}
money.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

const out = [
  '// GENERATED by packages/api-client/scripts/generate.mjs from docs/04-api/openapi.yaml. DO NOT EDIT BY HAND.',
  `// Contract version ${contract.info.version}. Regenerate with \`pnpm gen\`.`,
  '',
  '/** Money operations (`x-money: true`): `METHOD /path-template` -> operationId. They require Idempotency-Key. */',
  'export const moneyOperations: Readonly<Record<string, string>> = {',
  ...money.map((m) => `  '${m.method} ${m.path}': '${m.id}',`),
  '};',
  '',
].join('\n');
writeFileSync(join(outDir, 'operations.ts'), out);
console.log(`@mytask/api-client: ${money.length} money operations`);
