#!/usr/bin/env node
// @mytask/tokens build: tokens.json -> dist/ (CSS variables, fonts CSS, JS/TS object, React Native theme).
// Plain Node >= 18, no dependencies:  node packages/tokens/build.mjs
// Fails (exit 1) if an alias is broken or any contrast pair in contrast-pairs.json fails WCAG AA.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { here, loadJson, walk, resolve, aliasOf, typeOf, getPath } from './lib.mjs';
import { checkContrast } from './contrast.mjs';

const tokens = loadJson('tokens.json');
const out = join(here, 'dist');
mkdirSync(out, { recursive: true });
const PREFIX = 'mt';
const BANNER = '/* Generated by packages/tokens/build.mjs from tokens.json. Do not edit. */\n';

// ---------- naming ----------
const seg = (s) => String(s).replace(/\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
/** CSS custom property name for an absolute token path. Theme roles drop the "theme.<name>" prefix. */
function cssVar(pathArr) {
  let p = pathArr;
  if (p[0] === 'theme') {
    p = p.slice(2);
    if (p[0] === 'shadow') p = ['elevation', ...p.slice(1)];
  }
  return `--${PREFIX}-${p.map(seg).join('-')}`;
}

// ---------- value formatting ----------
const quoteFont = (f) => (/[\s-]/.test(f) && !/^(system-ui|sans-serif|monospace|ui-monospace|-apple-system)$/.test(f) ? `"${f}"` : f);
function cssValue(type, v) {
  switch (type) {
    case 'dimension': return typeof v === 'number' ? (v === 0 ? '0' : `${v}px`) : v;
    case 'duration': return `${v}ms`;
    case 'cubicBezier': return `cubic-bezier(${v.join(', ')})`;
    case 'fontFamily': return Array.isArray(v) ? v.map(quoteFont).join(', ') : quoteFont(v);
    case 'shadow': return v.length ? v.map((s) => `${s.offsetX}px ${s.offsetY}px ${s.blur}px ${s.spread}px ${s.color}`).join(', ') : 'none';
    default: return String(v);
  }
}

// ---------- CSS ----------
const primitiveLines = [];
const themeLines = { };
const skipCss = (path, type) => type === 'typography' || type === 'string' && path[0] === 'font' && (path[1] === 'native' || path[1] === 'webFiles');

for (const { path, token, type } of walk(tokens)) {
  if (skipCss(path, type)) continue;
  if (path[0] === 'theme') {
    const theme = path[1];
    const alias = aliasOf(token.$value);
    const value = alias ? `var(${cssVar(alias.split('.'))})` : cssValue(type, resolve(tokens, token.$value));
    (themeLines[theme] ??= []).push(`  ${cssVar(path)}: ${value};`);
    continue;
  }
  const alias = aliasOf(token.$value);
  const value = alias ? `var(${cssVar(alias.split('.'))})` : cssValue(type, resolve(tokens, token.$value));
  primitiveLines.push(`  ${cssVar(path)}: ${value};`);
}

// Typography utility classes (mobile-first, step up at breakpoint.lg)
const lg = resolve(tokens, tokens.breakpoint.lg.$value);
const textClasses = [];
const textClassesLg = [];
for (const [name, tok] of Object.entries(tokens.text)) {
  if (name.startsWith('$')) continue;
  const v = tok.$value;
  const ref = (k) => `var(${cssVar(aliasOf(v[k]).split('.'))})`;
  const extra = name.startsWith('price') ? '\n  font-variant-numeric: tabular-nums;' : '';
  textClasses.push(`.${PREFIX}-text-${seg(name)} {\n  font-family: ${ref('fontFamily')};\n  font-size: ${ref('fontSize')};\n  line-height: ${ref('lineHeight')};\n  font-weight: ${ref('fontWeight')};\n  letter-spacing: ${ref('letterSpacing')};\n  text-transform: none;${extra}\n}`);
  const up = tok.$extensions?.['ge.mytask.lg'];
  if (up) {
    const r = (k) => `var(${cssVar(aliasOf(up[k]).split('.'))})`;
    textClassesLg.push(`  .${PREFIX}-text-${seg(name)} { font-size: ${r('fontSize')}; line-height: ${r('lineHeight')}; }`);
  }
}

const durations = Object.keys(tokens.motion.duration).filter((k) => !k.startsWith('$') && k !== 'instant');
const css = `${BANNER}
/* Primitives (theme-independent). */
:root {
${primitiveLines.join('\n')}
}

/* Light theme = default (Q-059). */
:root,
[data-theme="light"] {
  color-scheme: light;
${themeLines.light.join('\n')}
}

/* Dark theme: set data-theme="dark" on <html> (web app stores the user's choice). */
[data-theme="dark"] {
  color-scheme: dark;
${themeLines.dark.join('\n')}
}

/* Reduced motion: every animated duration becomes 0. Components must also swap transforms for fades. */
@media (prefers-reduced-motion: reduce) {
  :root {
${durations.map((d) => `    --${PREFIX}-motion-duration-${seg(d)}: 0ms;`).join('\n')}
  }
}

/* Text styles */
${textClasses.join('\n')}
@media (min-width: ${lg}px) {
${textClassesLg.join('\n')}
}
`;
writeFileSync(join(out, 'tokens.css'), css);

// @font-face (web). The web/admin apps serve packages/assets/fonts/woff2 at /fonts/.
const fontFaces = Object.entries(tokens.font.webFiles)
  .filter(([k]) => !k.startsWith('$'))
  .map(([w, t]) => `@font-face {\n  font-family: "FiraGO";\n  font-style: normal;\n  font-weight: ${w};\n  font-display: swap;\n  src: url("/fonts/${t.$value.split('/').pop()}") format("woff2");\n}`)
  .join('\n');
writeFileSync(join(out, 'fonts.css'), `${BANNER}/* Serve packages/assets/fonts/woff2/* at /fonts/. One family, real weights 400/500/600/700. */\n${fontFaces}\n`);

// ---------- resolved JS object ----------
function resolvedTree(node, path = []) {
  if (node && typeof node === 'object' && !Array.isArray(node) && '$value' in node) {
    return resolve(tokens, node.$value);
  }
  const o = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    o[k] = resolvedTree(v, [...path, k]);
  }
  return o;
}
const all = resolvedTree(tokens);
const { theme: themes, ...primitives } = all;

// CSS var references, for CSS-in-JS / Tailwind preset on web: vars.bg.canvas === 'var(--mt-bg-canvas)'
function varTree(node, path) {
  if (node && typeof node === 'object' && !Array.isArray(node) && '$value' in node) return `var(${cssVar(path)})`;
  const o = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    o[k] = varTree(v, [...path, k]);
  }
  return o;
}
const { font: _f, text: _t, theme: _th, ...cssPrims } = tokens;
const webVars = { ...varTree(cssPrims, []), ...varTree(tokens.theme.light, ['theme', 'light']) };
webVars.textClass = Object.fromEntries(Object.keys(tokens.text).filter((k) => !k.startsWith('$')).map((k) => [k, `${PREFIX}-text-${seg(k)}`]));

// ---------- React Native theme ----------
function nativeText(style) {
  // style is resolved: { fontFamily: [...], fontSize, lineHeight, fontWeight, letterSpacing }
  return {
    fontFamily: primitives.font.native.family[String(style.fontWeight)],
    fontSize: style.fontSize,
    lineHeight: style.lineHeight,
    letterSpacing: style.letterSpacing,
  };
}
function nativeShadow(pathStr) {
  const node = getPath(tokens, pathStr);
  return node.$extensions?.['ge.mytask.native'] ?? {};
}
function nativeTheme(name) {
  const t = themes[name];
  const shadowRefs = tokens.theme[name].shadow;
  const shadows = Object.fromEntries(
    Object.entries(shadowRefs).filter(([k]) => !k.startsWith('$')).map(([k, v]) => [k, nativeShadow(aliasOf(v.$value))]),
  );
  const text = Object.fromEntries(Object.entries(primitives.text).map(([k, v]) => [k, {
    ...nativeText(v),
    ...(k.startsWith('price') ? { fontVariant: ['tabular-nums'] } : {}),
  }]));
  const { shadow: _s, ...colors } = t;
  return {
    name,
    dark: name === 'dark',
    colors,
    text,
    shadow: shadows,
    space: primitives.space,
    radius: primitives.radius,
    borderWidth: primitives.borderWidth,
    size: primitives.size,
    zIndex: primitives.zIndex,
    motion: primitives.motion,
    focus: { ...primitives.focus, ring: t.focus.ring },
    fonts: primitives.font.native,
  };
}
const native = { light: nativeTheme('light'), dark: nativeTheme('dark') };

// ---------- write JS + d.ts ----------
const js = (name, obj) => `export const ${name} = ${JSON.stringify(obj, null, 2)};\n`;
const dts = (name, obj) => `export declare const ${name}: ${JSON.stringify(obj, null, 2)};\n`;

writeFileSync(join(out, 'tokens.mjs'), BANNER + js('primitives', primitives) + js('themes', themes));
writeFileSync(join(out, 'tokens.d.ts'), BANNER + dts('primitives', primitives) + dts('themes', themes));

writeFileSync(join(out, 'web.mjs'), BANNER + js('vars', webVars));
writeFileSync(join(out, 'web.d.ts'), BANNER + dts('vars', webVars));

writeFileSync(join(out, 'native.mjs'), BANNER + js('lightTheme', native.light) + js('darkTheme', native.dark) + 'export const themes = { light: lightTheme, dark: darkTheme };\n');
writeFileSync(join(out, 'native.d.ts'), BANNER + dts('lightTheme', native.light) + dts('darkTheme', native.dark) +
  'export type Theme = typeof lightTheme | typeof darkTheme;\nexport declare const themes: { light: typeof lightTheme; dark: typeof darkTheme };\n');

// ---------- contrast gate ----------
const rows = checkContrast(tokens);
const fails = rows.filter((r) => !r.pass);
const count = [...walk(tokens)].length;
console.log(`@mytask/tokens: ${count} tokens -> dist/tokens.css, fonts.css, tokens.mjs(.d.ts), web.mjs(.d.ts), native.mjs(.d.ts)`);
console.log(`Contrast: ${rows.length} checks, ${fails.length} failures.`);
for (const f of fails) console.log(`  FAIL ${f.theme}: ${f.fg} on ${f.bg} = ${f.ratio.toFixed(2)} < ${f.min}`);
// sanity: every theme defines the same role keys
const keys = (o, p = '') => Object.entries(o).flatMap(([k, v]) => (v && typeof v === 'object' && !Array.isArray(v) ? keys(v, `${p}${k}.`) : [`${p}${k}`]));
const lk = new Set(keys(themes.light));
const dk = new Set(keys(themes.dark));
const diff = [...lk].filter((k) => !dk.has(k)).concat([...dk].filter((k) => !lk.has(k)));
if (diff.length) console.log(`  Theme key mismatch: ${diff.join(', ')}`);
process.exit(fails.length || diff.length ? 1 : 0);
void typeOf;
