// Code-defined settings registry (ADR-005): the register rows implemented so far, with the metadata the admin
// settings screen shows (spec 16 AC-51). Defaults = approved launch values of the spec 00 register ("prod → x" rows
// use x, Q-068). Every row behind a `PublicConfig` field is here and marked `public`; other rows come with their slices. Meanings: English from spec 00, Georgian alongside (Q-058).
import type { components } from '@mytask/types';
import type { StoredSecret } from './secret-box';

type Permission = components['schemas']['PermissionCode'];
type Area = components['schemas']['SettingArea'];
type Type = components['schemas']['SettingType'];

interface RowMeta<D> {
  key: string;
  default: D;
  area: Area;
  type: Type;
  unit?: string;
  meaning: { en: string; ka: string };
  allowedValues?: string[];
  minimum?: number;
  maximum?: number;
  source: string;
  tag: string;
  /** Changing it emails every S-100 address (EV-124, spec 16 AC-55). */
  critical?: boolean;
  /** Needs a re-login within 15 minutes (spec 16 AC-7, Q-145). */
  stepUp?: boolean;
  /** Social-login provider row with an encrypted write-only secret (ADR-005 §8, Q-155). */
  socialProvider?: boolean;
  /** Exposed to clients through `getPublicConfig` (ADR-005 §1, §9). */
  public?: boolean;
  /** `null` is a valid value: unlimited for limits (R-2.2), empty for texts and images. */
  nullable?: boolean;
  writePermission: Permission;
}

const row = <D>(m: RowMeta<D>) => m;

/** Money row value (contract `Money`): integer tetri, never a float (ADR-003). */
export interface MoneyValue {
  amount: number;
  currency: 'GEL';
}
const gel = (tetri: number): MoneyValue => ({ amount: tetri, currency: 'GEL' });

/** Admin-edited text in both languages (contract `LocalizedString`); `en` null → readers get `ka`. */
export interface LocalizedText {
  ka: string;
  en: string | null;
}

/** Stored value of S-111 (legacy `settings_general`). Images are file ids of ready public images. */
export interface BrandingStored {
  siteTitle: string;
  siteSubtitle: string | null;
  titleSeparator: string;
  logoFileId: string | null;
  logoDarkFileId: string | null;
  logoTransparentFileId: string | null;
  faviconFileId: string | null;
}

/** Stored value of S-112. */
export interface AnnouncementStored {
  text: LocalizedText | null;
  url: string | null;
}

/** Stored value of S-113 (legacy `settings_hero`). */
export interface HeroStored {
  title: LocalizedText | null;
  subtitle: LocalizedText | null;
  imageFileIds: string[];
}

/** Stored value of S-114 (legacy `settings_footer`). */
export interface FooterStored {
  links: { label: string; url: string }[];
  socialLinks: { network: string; url: string }[];
  logos: { name: string; imageFileId: string; linkUrl: string | null }[];
}

/** Stored value of S-115 (legacy `settings_seo`). */
export interface SeoDefaultsStored {
  metaDescription: LocalizedText | null;
  keywords: string | null;
  ogImageFileId: string | null;
  facebookPageUrl: string | null;
  facebookAppId: string | null;
  twitterUsername: string | null;
}

/** Stored value of S-121 (data-model §3.K, spec 16 AC-70): the register's boolean is `enabled`. */
export interface MaintenanceStored {
  enabled: boolean;
  headline: LocalizedText | null;
  message: LocalizedText | null;
}

/** Stored value of S-065…S-069 (ADR-005 §8): the secret is sealed by SecretBox, never returned. */
export interface SocialProviderStored {
  isEnabled: boolean;
  clientId: string | null;
  clientSecret: StoredSecret | null;
}
const SOCIAL_OFF: SocialProviderStored = { isEnabled: false, clientId: null, clientSecret: null };

export const settingsRegistry = {
  // 4.1 Plans and limits (null = unlimited, 0 = not allowed, R-2.2)
  'S-001': row({
    key: 'plans.standard.gig_limit',
    default: 1 as number | null,
    area: 'plans',
    type: 'integer',
    minimum: 0,
    nullable: true,
    meaning: {
      en: 'Max non-deleted gigs a Standard user may have (empty = unlimited)',
      ka: 'Standard მომხმარებლის არაწაშლილი სერვისების მაქსიმალური რაოდენობა (ცარიელი = შეუზღუდავი)',
    },
    source: 'BR-021, Q-021',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-002': row({
    key: 'plans.premium.gig_limit',
    default: null as number | null,
    area: 'plans',
    type: 'integer',
    minimum: 0,
    nullable: true,
    meaning: {
      en: 'Max non-deleted gigs a Premium user may have (empty = unlimited)',
      ka: 'Premium მომხმარებლის არაწაშლილი სერვისების მაქსიმალური რაოდენობა (ცარიელი = შეუზღუდავი)',
    },
    source: 'BR-110, Q-021',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-003': row({
    key: 'plans.standard.project_limit',
    default: null as number | null,
    area: 'plans',
    type: 'integer',
    minimum: 0,
    nullable: true,
    meaning: {
      en: 'Max counted projects for Standard (empty = unlimited)',
      ka: 'Standard მომხმარებლის პროექტების მაქსიმალური რაოდენობა (ცარიელი = შეუზღუდავი)',
    },
    source: 'Q-021',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-004': row({
    key: 'plans.premium.project_limit',
    default: null as number | null,
    area: 'plans',
    type: 'integer',
    minimum: 0,
    nullable: true,
    meaning: {
      en: 'Max counted projects for Premium (empty = unlimited)',
      ka: 'Premium მომხმარებლის პროექტების მაქსიმალური რაოდენობა (ცარიელი = შეუზღუდავი)',
    },
    source: 'Q-021',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-005': row({
    key: 'plans.standard.custom_offer_limit',
    default: null as number | null,
    area: 'plans',
    type: 'integer',
    minimum: 0,
    nullable: true,
    meaning: {
      en: 'Max counted custom offers a Standard freelancer may have; used only if S-007 is ON (empty = unlimited)',
      ka: 'Standard ფრილანსერის ინდივიდუალური შეთავაზებების მაქსიმალური რაოდენობა; გამოიყენება მხოლოდ თუ S-007 ჩართულია (ცარიელი = შეუზღუდავი)',
    },
    source: 'Q-021, Q-060e',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-006': row({
    key: 'plans.premium.custom_offer_limit',
    default: null as number | null,
    area: 'plans',
    type: 'integer',
    minimum: 0,
    nullable: true,
    meaning: {
      en: 'Max counted custom offers a Premium freelancer may have; used only if S-007 is ON (empty = unlimited)',
      ka: 'Premium ფრილანსერის ინდივიდუალური შეთავაზებების მაქსიმალური რაოდენობა; გამოიყენება მხოლოდ თუ S-007 ჩართულია (ცარიელი = შეუზღუდავი)',
    },
    source: 'Q-021, Q-060e',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-007': row({
    key: 'custom_offers.count_toward_plan_limit',
    default: false,
    area: 'plans',
    type: 'boolean',
    meaning: {
      en: 'Whether custom offers are counted against S-005/S-006',
      ka: 'ითვლება თუ არა ინდივიდუალური შეთავაზებები S-005/S-006 ლიმიტში',
    },
    source: 'Q-060e',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-008': row({
    key: 'plans.premium.monthly_price',
    default: gel(999),
    area: 'plans',
    type: 'money',
    unit: 'GEL',
    minimum: 0,
    meaning: { en: 'Premium price per month', ka: 'Premium-ის თვიური ფასი' },
    source: 'BR-110',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  'S-009': row({
    key: 'plans.premium.yearly_price',
    default: gel(9999),
    area: 'plans',
    type: 'money',
    unit: 'GEL',
    minimum: 0,
    meaning: { en: 'Premium price per year', ka: 'Premium-ის წლიური ფასი' },
    source: 'BR-110, Q-019',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.plans.write',
  }),
  // 4.3 Payment methods and wallet
  'S-019': row({
    key: 'payments.bog_card.enabled',
    default: true,
    area: 'payments',
    type: 'boolean',
    meaning: {
      en: 'Pay by BOG card (checkout, top-up, subscription)',
      ka: 'გადახდა BOG ბარათით (შეკვეთა, ბალანსის შევსება, გამოწერა)',
    },
    source: 'Q-016',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.payments.write',
  }),
  'S-020': row({
    key: 'payments.wallet.enabled',
    default: true,
    area: 'payments',
    type: 'boolean',
    meaning: { en: 'Pay from Available balance', ka: 'გადახდა ხელმისაწვდომი ბალანსიდან' },
    source: 'Q-016, BR-034',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.payments.write',
  }),
  'S-021': row({
    key: 'payments.bank_transfer.enabled',
    default: false,
    area: 'payments',
    type: 'boolean',
    meaning: {
      en: 'Offline bank transfer with manual admin approval',
      ka: 'საბანკო გადარიცხვა ადმინისტრატორის ხელით დადასტურებით',
    },
    source: 'Q-016',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.payments.write',
  }),
  'S-022': row({
    key: 'wallet.topup.enabled',
    default: true,
    area: 'payments',
    type: 'boolean',
    meaning: { en: 'Wallet top-up by card', ka: 'ბალანსის შევსება ბარათით' },
    source: 'Q-030, BR-100',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.payments.write',
  }),
  'S-023': row({
    key: 'wallet.topup.min_amount',
    default: gel(100),
    area: 'payments',
    type: 'money',
    unit: 'GEL',
    minimum: 1,
    meaning: { en: 'Minimum top-up', ka: 'ბალანსის შევსების მინიმალური თანხა' },
    source: 'BogSeeder.php:28, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.payments.write',
  }),
  'S-024': row({
    key: 'wallet.topup.max_amount',
    default: gel(90_000_000),
    area: 'payments',
    type: 'money',
    unit: 'GEL',
    minimum: 1,
    meaning: { en: 'Maximum top-up', ka: 'ბალანსის შევსების მაქსიმალური თანხა' },
    source: 'BogSeeder.php:29, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.payments.write',
  }),
  // 4.4 Escrow timers, 4.5 refunds
  'S-025': row({
    key: 'escrow.auto_release.enabled',
    default: true,
    area: 'escrow',
    type: 'boolean',
    meaning: {
      en: 'Release funds automatically after buyer silence following a delivery',
      ka: 'თანხის ავტომატური გათავისუფლება, თუ მყიდველი ჩაბარების შემდეგ არ პასუხობს',
    },
    source: 'Q-051, Q-009',
    tag: 'CHANGE',
    public: true,
    writePermission: 'settings.escrow.write',
  }),
  'S-026': row({
    key: 'escrow.auto_release.hours',
    default: 72,
    area: 'escrow',
    type: 'integer',
    unit: 'hours',
    minimum: 1,
    meaning: {
      en: 'Hours of buyer silence after delivery before auto-release',
      ka: 'მყიდველის უპასუხობის საათები ჩაბარების შემდეგ ავტომატურ გათავისუფლებამდე',
    },
    source: 'Q-051, Q-067a, Q-061b, Q-067c',
    tag: 'CHANGE',
    public: true,
    writePermission: 'settings.escrow.write',
  }),
  'S-027': row({
    key: 'projects.award_acceptance_hours',
    default: 48,
    area: 'escrow',
    type: 'integer',
    unit: 'hours',
    minimum: 1,
    meaning: {
      en: 'Time the awarded freelancer has to accept before the award is removed',
      ka: 'დრო, რომელშიც არჩეულმა ფრილანსერმა უნდა დაადასტუროს, სანამ არჩევანი გაუქმდება',
    },
    source: 'Q-005, BR-060',
    tag: 'CHANGE',
    public: true,
    writePermission: 'settings.escrow.write',
  }),
  'S-028': row({
    key: 'escrow.unblock_request.wait_hours',
    default: 72,
    area: 'escrow',
    type: 'integer',
    unit: 'hours',
    minimum: 0,
    meaning: {
      en: 'Hours after the latest delivery before a freelancer may ask the admin to release funds',
      ka: 'საათები ბოლო ჩაბარების შემდეგ, სანამ ფრილანსერი ადმინისტრატორს თანხის გათავისუფლებას სთხოვს',
    },
    source: 'BR-086',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.escrow.write',
  }),
  'S-029': row({
    key: 'escrow.unblock_request.available_when_auto_release_on',
    default: false,
    area: 'escrow',
    type: 'boolean',
    meaning: {
      en: 'Whether the freelancer "unblock request" exists while S-025 is ON',
      ka: 'ხელმისაწვდომია თუ არა ფრილანსერის „განბლოკვის მოთხოვნა“, როცა S-025 ჩართულია',
    },
    source: 'Q-067b',
    tag: 'ACCEPTED P-5',
    public: true,
    writePermission: 'settings.escrow.write',
  }),
  'S-030': row({
    key: 'refunds.seller_response_days',
    default: 2,
    area: 'escrow',
    type: 'integer',
    unit: 'days',
    minimum: 1,
    meaning: {
      en: 'Days a seller has to answer a refund request before it becomes "rejected by seller"',
      ka: 'დღეები, რომელშიც გამყიდველმა უნდა უპასუხოს თანხის დაბრუნების მოთხოვნას, სანამ ის „გამყიდველის მიერ უარყოფილი“ გახდება',
    },
    source: 'Q-012, BR-082',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.escrow.write',
  }),
  // 4.6 Withdrawals
  'S-031': row({
    key: 'withdrawals.min_amount',
    default: gel(1000),
    area: 'withdrawals',
    type: 'money',
    unit: 'GEL',
    minimum: 0,
    meaning: { en: 'Minimum withdrawal request', ka: 'თანხის გატანის მინიმალური მოთხოვნა' },
    source: 'BR-101, Q-004, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.withdrawals.write',
  }),
  'S-032': row({
    key: 'withdrawals.period',
    default: 'daily' as 'daily' | 'weekly' | 'monthly',
    area: 'withdrawals',
    type: 'enum',
    allowedValues: ['daily', 'weekly', 'monthly'],
    meaning: {
      en: 'Minimum time since the last paid withdrawal: daily = 24h, weekly = 168h, monthly = 720h',
      ka: 'მინიმალური დრო ბოლო გადახდილი გატანიდან: ყოველდღიური = 24სთ, ყოველკვირეული = 168სთ, ყოველთვიური = 720სთ',
    },
    source: 'BR-101, Q-004, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.withdrawals.write',
  }),
  // 4.7 Custom offers, 4.8 revisions
  'S-034': row({
    key: 'custom_offers.enabled',
    default: true,
    area: 'marketplace',
    type: 'boolean',
    meaning: {
      en: 'Custom-offer feature ON/OFF',
      ka: 'ინდივიდუალური შეთავაზებების ფუნქცია ჩართვა/გამორთვა',
    },
    source: 'Q-027, Q-060a, Q-068c',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-035': row({
    key: 'custom_offers.require_admin_approval',
    default: false,
    area: 'marketplace',
    type: 'boolean',
    meaning: {
      en: 'Offers need admin approval before the buyer sees them',
      ka: 'შეთავაზებებს სჭირდება ადმინისტრატორის დადასტურება, სანამ მყიდველი დაინახავს',
    },
    source: 'Q-060b',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-036': row({
    key: 'custom_offers.expiry_days',
    default: 3,
    area: 'marketplace',
    type: 'integer',
    unit: 'days',
    minimum: 1,
    meaning: {
      en: 'Days before an unanswered offer expires',
      ka: 'დღეები, რის შემდეგაც უპასუხო შეთავაზებას ვადა გასდის',
    },
    source: 'Q-060c',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-037': row({
    key: 'custom_offers.attachments.enabled',
    default: true,
    area: 'marketplace',
    type: 'boolean',
    meaning: { en: 'Attachments on offers', ka: 'ფაილების მიმაგრება შეთავაზებებზე' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-038': row({
    key: 'custom_offers.attachments.max_size_mb',
    default: 50,
    area: 'marketplace',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: {
      en: 'Max size per offer attachment',
      ka: 'შეთავაზების ერთი ფაილის მაქსიმალური ზომა',
    },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-039': row({
    key: 'custom_offers.attachments.max_files',
    default: 10,
    area: 'marketplace',
    type: 'integer',
    unit: 'count',
    minimum: 0,
    meaning: { en: 'Max files per offer', ka: 'ფაილების მაქსიმალური რაოდენობა ერთ შეთავაზებაზე' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-040': row({
    key: 'custom_offers.attachments.allowed_extensions',
    default: ['png', 'jpg', 'zip', 'pdf', 'psd', 'mp4', 'mp3'] as string[],
    area: 'marketplace',
    type: 'list',
    meaning: {
      en: 'Allowed offer attachment file types',
      ka: 'შეთავაზების ფაილების დაშვებული ტიპები',
    },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-041': row({
    key: 'revisions.max_allowed',
    default: 10,
    area: 'marketplace',
    type: 'integer',
    minimum: 0,
    meaning: {
      en: 'Highest number of revisions a freelancer may choose on a gig, proposal or custom offer',
      ka: 'რევიზიების მაქსიმალური რაოდენობა, რომელსაც ფრილანსერი ირჩევს სერვისზე, წინადადებაზე ან შეთავაზებაზე',
    },
    source: 'Q-056, Q-061a',
    tag: 'ACCEPTED P-1',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  // 4.9 Subscriptions, points
  'S-045': row({
    key: 'points.per_premium_month',
    default: 100,
    area: 'subscriptions',
    type: 'integer',
    unit: 'points',
    minimum: 0,
    meaning: {
      en: 'Points needed for 1 month of Premium (monthly plan only)',
      ka: 'Premium-ის 1 თვისთვის საჭირო ქულები (მხოლოდ თვიური გეგმა)',
    },
    source: 'Q-052, BR-114',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.subscriptions.write',
  }),
  'S-046': row({
    key: 'points.events.referral_signup',
    default: 10,
    area: 'subscriptions',
    type: 'integer',
    unit: 'points',
    minimum: 0,
    meaning: {
      en: 'Points the referrer earns when the referred user is verified (or registers, if verification is off)',
      ka: 'ქულები, რომლებსაც მომწვევი იღებს, როცა მოწვეული მომხმარებელი ვერიფიცირდება (ან რეგისტრირდება, თუ ვერიფიკაცია გამორთულია)',
    },
    source: 'BR-115, Q-017',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.subscriptions.write',
  }),
  'S-052': row({
    key: 'auth.email_verification.required',
    default: false,
    area: 'auth',
    type: 'boolean',
    meaning: {
      en: 'New accounts must be verified before becoming active',
      ka: 'ახალი ანგარიშები აქტიურდება მხოლოდ ვერიფიკაციის შემდეგ',
    },
    source: 'BR-002',
    tag: 'LEGACY',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-053': row({
    key: 'auth.email_verification.method',
    default: 'admin' as 'email' | 'admin',
    area: 'auth',
    type: 'enum',
    allowedValues: ['email', 'admin'],
    meaning: {
      en: 'Verification by email link, or manual admin approval',
      ka: 'ვერიფიკაცია ელ-ფოსტის ბმულით ან ადმინისტრატორის ხელით დადასტურებით',
    },
    source: 'BR-003',
    tag: 'LEGACY',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-054': row({
    key: 'auth.email_verification.link_expiry_minutes',
    default: 60,
    area: 'auth',
    type: 'integer',
    unit: 'minutes',
    minimum: 5,
    maximum: 10080,
    meaning: { en: 'Validity of the verification link', ka: 'ვერიფიკაციის ბმულის მოქმედების ვადა' },
    source: 'BR-003',
    tag: 'LEGACY',
    writePermission: 'settings.auth.write',
  }),
  'S-055': row({
    key: 'auth.password_reset.link_expiry_minutes',
    default: 60,
    area: 'auth',
    type: 'integer',
    unit: 'minutes',
    minimum: 5,
    maximum: 1440,
    meaning: {
      en: 'Validity of the password-reset link',
      ka: 'პაროლის აღდგენის ბმულის მოქმედების ვადა',
    },
    source: 'BR-007',
    tag: 'LEGACY',
    writePermission: 'settings.auth.write',
  }),
  'S-056': row({
    key: 'auth.two_factor.enabled',
    default: true,
    area: 'auth',
    type: 'boolean',
    meaning: {
      en: 'Global email-2FA switch. ON = users may turn 2FA on for their own account. OFF = 2FA option hidden (choices are remembered)',
      ka: 'ელ-ფოსტით ორსაფეხურიანი ავტორიზაციის ზოგადი გადამრთველი. ჩართული = მომხმარებლებს შეუძლიათ საკუთარ ანგარიშზე ჩართვა. გამორთული = ოფცია დამალულია (არჩევანი ინახება)',
    },
    source: 'Q-043, Q-063, Q-072',
    tag: 'NEW',
    critical: true,
    stepUp: true,
    public: true,
    writePermission: 'settings.auth.write',
  }),
  'S-057': row({
    key: 'auth.two_factor.code_ttl_minutes',
    default: 10,
    area: 'auth',
    type: 'integer',
    unit: 'minutes',
    minimum: 1,
    maximum: 60,
    meaning: {
      en: 'Validity of the emailed code',
      ka: 'ელ-ფოსტით გამოგზავნილი კოდის მოქმედების ვადა',
    },
    source: 'Q-063',
    tag: 'NEW',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-058': row({
    key: 'auth.two_factor.max_attempts',
    default: 5,
    area: 'auth',
    type: 'integer',
    minimum: 1,
    maximum: 20,
    meaning: {
      en: 'Wrong codes allowed before the code is invalidated',
      ka: 'არასწორი კოდების რაოდენობა, რომლის შემდეგაც კოდი უქმდება',
    },
    source: 'Q-063',
    tag: 'NEW',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-059': row({
    key: 'auth.two_factor.trusted_device_days',
    default: 30,
    area: 'auth',
    type: 'integer',
    unit: 'days',
    minimum: 1,
    maximum: 365,
    meaning: {
      en: 'How long a device stays trusted after a successful 2FA login',
      ka: 'რამდენ ხანს რჩება მოწყობილობა სანდო წარმატებული ორსაფეხურიანი შესვლის შემდეგ',
    },
    source: 'Q-063',
    tag: 'NEW',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-060': row({
    key: 'auth.two_factor.staff_required',
    default: true,
    area: 'auth',
    type: 'boolean',
    meaning: {
      en: 'Email 2FA required for staff/admin logins, whatever S-056 says',
      ka: 'ელ-ფოსტით ორსაფეხურიანი ავტორიზაცია სავალდებულოა ადმინისტრატორებისთვის, S-056-ის მიუხედავად',
    },
    source: 'Q-063b, P-4',
    tag: 'NEW',
    critical: true,
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-061': row({
    key: 'auth.recaptcha.enabled',
    default: false,
    area: 'auth',
    type: 'boolean',
    meaning: {
      en: 'reCAPTCHA on register, login, contact (keys in .env)',
      ka: 'reCAPTCHA რეგისტრაციაზე, შესვლაზე და საკონტაქტო ფორმაზე (გასაღებები .env-ში)',
    },
    source: 'BR-001',
    tag: 'LEGACY',
    stepUp: true,
    public: true,
    writePermission: 'settings.auth.write',
  }),
  'S-062': row({
    key: 'auth.login_throttle.max_attempts',
    default: 5,
    area: 'auth',
    type: 'integer',
    minimum: 1,
    maximum: 50,
    meaning: {
      en: 'Failed user logins (per account + IP) within 15 minutes before a temporary lock',
      ka: 'მომხმარებლის წარუმატებელი შესვლები (ანგარიში + IP) 15 წუთში დროებით დაბლოკვამდე',
    },
    source: 'R-043',
    tag: 'NEW',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-063': row({
    key: 'auth.login_throttle.lock_minutes',
    default: 15,
    area: 'auth',
    type: 'integer',
    unit: 'minutes',
    minimum: 1,
    maximum: 1440,
    meaning: {
      en: 'Lock duration after S-062 is reached',
      ka: 'დაბლოკვის ხანგრძლივობა S-062-ის მიღწევის შემდეგ',
    },
    source: 'R-043',
    tag: 'NEW',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-064': row({
    key: 'security.staff_login.ip_ban_threshold',
    default: 3,
    area: 'auth',
    type: 'integer',
    minimum: 1,
    maximum: 100,
    meaning: {
      en: 'Failed staff logins from one IP before the IP is banned from the staff login',
      ka: 'ადმინისტრატორის წარუმატებელი შესვლები ერთი IP-დან, რის შემდეგაც IP იბლოკება',
    },
    source: 'BR-004',
    tag: 'LEGACY',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-065': row({
    key: 'auth.social.google',
    default: SOCIAL_OFF,
    area: 'auth',
    type: 'structured',
    meaning: {
      en: 'Google login: enabled + client ID + client secret (write-only)',
      ka: 'Google-ით შესვლა: ჩართვა + client ID + client secret (მხოლოდ ჩაწერა)',
    },
    source: 'Q-032, BR-006',
    tag: 'LEGACY',
    critical: true,
    stepUp: true,
    socialProvider: true,
    writePermission: 'settings.auth.write',
  }),
  'S-066': row({
    key: 'auth.social.facebook',
    default: SOCIAL_OFF,
    area: 'auth',
    type: 'structured',
    meaning: {
      en: 'Facebook login: enabled + client ID + client secret (write-only)',
      ka: 'Facebook-ით შესვლა: ჩართვა + client ID + client secret (მხოლოდ ჩაწერა)',
    },
    source: 'Q-032',
    tag: 'LEGACY',
    critical: true,
    stepUp: true,
    socialProvider: true,
    writePermission: 'settings.auth.write',
  }),
  'S-067': row({
    key: 'auth.social.github',
    default: SOCIAL_OFF,
    area: 'auth',
    type: 'structured',
    meaning: {
      en: 'GitHub login: enabled + client ID + client secret (write-only)',
      ka: 'GitHub-ით შესვლა: ჩართვა + client ID + client secret (მხოლოდ ჩაწერა)',
    },
    source: 'Q-032',
    tag: 'LEGACY',
    critical: true,
    stepUp: true,
    socialProvider: true,
    writePermission: 'settings.auth.write',
  }),
  'S-068': row({
    key: 'auth.social.linkedin',
    default: SOCIAL_OFF,
    area: 'auth',
    type: 'structured',
    meaning: {
      en: 'LinkedIn login: enabled + client ID + client secret (write-only)',
      ka: 'LinkedIn-ით შესვლა: ჩართვა + client ID + client secret (მხოლოდ ჩაწერა)',
    },
    source: 'Q-032',
    tag: 'LEGACY',
    critical: true,
    stepUp: true,
    socialProvider: true,
    writePermission: 'settings.auth.write',
  }),
  'S-069': row({
    key: 'auth.social.twitter',
    default: SOCIAL_OFF,
    area: 'auth',
    type: 'structured',
    meaning: {
      en: 'Twitter/X login: enabled + client ID + client secret (write-only)',
      ka: 'Twitter/X-ით შესვლა: ჩართვა + client ID + client secret (მხოლოდ ჩაწერა)',
    },
    source: 'Q-032',
    tag: 'LEGACY',
    critical: true,
    stepUp: true,
    socialProvider: true,
    writePermission: 'settings.auth.write',
  }),
  // 4.12 Projects
  'S-075': row({
    key: 'projects.enabled',
    default: true,
    area: 'marketplace',
    type: 'boolean',
    meaning: { en: 'Projects feature ON/OFF', ka: 'პროექტების ფუნქცია ჩართვა/გამორთვა' },
    source: 'BR-050',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  'S-076': row({
    key: 'projects.max_skills',
    default: 5,
    area: 'marketplace',
    type: 'integer',
    unit: 'count',
    minimum: 0,
    meaning: { en: 'Max skills on a project', ka: 'უნარების მაქსიმალური რაოდენობა პროექტზე' },
    source: '2023_06_10_192045_add_max_skills, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.marketplace.write',
  }),
  // 4.13 Uploads and media
  'S-077': row({
    key: 'media.gig.max_images',
    default: 10,
    area: 'media',
    type: 'integer',
    unit: 'count',
    minimum: 0,
    meaning: { en: 'Images per gig', ka: 'სურათების რაოდენობა ერთ სერვისზე' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-078': row({
    key: 'media.images.max_size_mb',
    default: 5,
    area: 'media',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: {
      en: 'Max size of a gig image and project thumbnail',
      ka: 'სერვისის სურათისა და პროექტის მინიატურის მაქსიმალური ზომა',
    },
    source: 'SettingsPublishTableSeeder.php, BR-051, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-079': row({
    key: 'media.gig.video_enabled',
    default: true,
    area: 'media',
    type: 'boolean',
    meaning: { en: 'Video link on gigs', ka: 'ვიდეო ბმული სერვისებზე' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-080': row({
    key: 'media.gig.documents_enabled',
    default: true,
    area: 'media',
    type: 'boolean',
    meaning: { en: 'Documents on gigs', ka: 'დოკუმენტები სერვისებზე' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-081': row({
    key: 'media.gig.max_documents',
    default: 2,
    area: 'media',
    type: 'integer',
    unit: 'count',
    minimum: 0,
    meaning: { en: 'Documents per gig', ka: 'დოკუმენტების რაოდენობა ერთ სერვისზე' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-082': row({
    key: 'media.gig.max_document_size_mb',
    default: 10,
    area: 'media',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: { en: 'Max document size', ka: 'დოკუმენტის მაქსიმალური ზომა' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-083': row({
    key: 'media.gig.max_tags',
    default: 5,
    area: 'media',
    type: 'integer',
    unit: 'count',
    minimum: 0,
    meaning: { en: 'Tags per gig', ka: 'თეგების რაოდენობა ერთ სერვისზე' },
    source: 'SettingsPublishTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-084': row({
    key: 'media.requirements.max_file_size_mb',
    default: 50,
    area: 'media',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: {
      en: 'Max file size in buyer order requirements',
      ka: 'მყიდველის შეკვეთის მოთხოვნების ფაილის მაქსიმალური ზომა',
    },
    source: 'SettingsMediaTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-085': row({
    key: 'media.requirements.allowed_extensions',
    default: ['jpg', 'jpeg', 'pdf', 'zip'] as string[],
    area: 'media',
    type: 'list',
    meaning: { en: 'Allowed requirement file types', ka: 'მოთხოვნების ფაილების დაშვებული ტიპები' },
    source: 'SettingsMediaTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-086': row({
    key: 'media.delivery.max_file_size_mb',
    default: 50,
    area: 'media',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: {
      en: 'Max file size of delivered work (gigs, projects)',
      ka: 'ჩაბარებული სამუშაოს ფაილის მაქსიმალური ზომა (სერვისები, პროექტები)',
    },
    source: 'SettingsMediaTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-087': row({
    // Legacy has no seed value (Q-068): empty = the purpose's fixed list until production is imported.
    key: 'media.delivery.allowed_extensions',
    default: [] as string[],
    area: 'media',
    type: 'list',
    meaning: {
      en: 'Allowed delivered-work file types',
      ka: 'ჩაბარებული სამუშაოს ფაილების დაშვებული ტიპები',
    },
    source: '2023_09_17_141442, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-088': row({
    key: 'media.audio_upload.enabled',
    default: false,
    area: 'media',
    type: 'boolean',
    meaning: { en: 'Audio uploads allowed', ka: 'აუდიო ფაილების ატვირთვა დაშვებულია' },
    source: '2023_09_17_141415, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-089': row({
    key: 'media.portfolio.max_images',
    default: 10,
    area: 'media',
    type: 'integer',
    unit: 'count',
    minimum: 0,
    meaning: {
      en: 'Images per portfolio item',
      ka: 'სურათების რაოდენობა პორტფოლიოს ერთ ნამუშევარზე',
    },
    source: 'SettingsMediaTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-090': row({
    key: 'media.portfolio.max_size_mb',
    default: 5,
    area: 'media',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: { en: 'Max portfolio image size', ka: 'პორტფოლიოს სურათის მაქსიმალური ზომა' },
    source: 'SettingsMediaTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-091': row({
    key: 'media.appeal.max_files',
    default: 2,
    area: 'media',
    type: 'integer',
    unit: 'count',
    minimum: 0,
    meaning: {
      en: 'Files per restriction appeal',
      ka: 'ფაილების რაოდენობა შეზღუდვის გასაჩივრებაზე',
    },
    source: '2023_10_29_211112, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-092': row({
    key: 'media.appeal.max_size_mb',
    default: 100,
    area: 'media',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: { en: 'Max appeal file size', ka: 'გასაჩივრების ფაილის მაქსიმალური ზომა' },
    source: 'Q-154',
    tag: 'LEGACY, value CHANGE',
    public: true,
    writePermission: 'settings.media.write',
  }),
  'S-093': row({
    key: 'media.appeal.allowed_extensions',
    default: [
      'jpg',
      'jpeg',
      'png',
      'gif',
      'webp',
      'pdf',
      'doc',
      'docx',
      'txt',
      'mp4',
      'mov',
      'avi',
      'mkv',
      'webm',
    ] as string[],
    area: 'media',
    type: 'list',
    meaning: { en: 'Allowed appeal file types', ka: 'გასაჩივრების ფაილების დაშვებული ტიპები' },
    source: 'Q-154',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.media.write',
  }),
  // 4.14 Chat
  'S-094': row({
    key: 'chat.attachments.enabled',
    default: true,
    area: 'chat',
    type: 'boolean',
    meaning: { en: 'Attachments in chat', ka: 'ფაილების მიმაგრება ჩატში' },
    source: 'LiveChatSettingsTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.chat.write',
  }),
  'S-095': row({
    key: 'chat.attachments.allowed_images',
    default: ['jpg', 'jpeg', 'png', 'gif'] as string[],
    area: 'chat',
    type: 'list',
    meaning: { en: 'Allowed chat image types', ka: 'ჩატის სურათების დაშვებული ტიპები' },
    source: 'LiveChatSettingsTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.chat.write',
  }),
  'S-096': row({
    key: 'chat.attachments.allowed_files',
    default: ['zip', 'pdf', 'txt', 'psd'] as string[],
    area: 'chat',
    type: 'list',
    meaning: { en: 'Allowed chat file types', ka: 'ჩატის ფაილების დაშვებული ტიპები' },
    source: 'LiveChatSettingsTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.chat.write',
  }),
  'S-097': row({
    key: 'chat.attachments.max_size_mb',
    default: 20,
    area: 'chat',
    type: 'integer',
    unit: 'MB',
    minimum: 0,
    meaning: { en: 'Max chat attachment size', ka: 'ჩატის ფაილის მაქსიმალური ზომა' },
    source: 'LiveChatSettingsTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.chat.write',
  }),
  'S-098': row({
    key: 'chat.emojis.enabled',
    default: true,
    area: 'chat',
    type: 'boolean',
    meaning: { en: 'Emoji picker', ka: 'ემოჯების არჩევა' },
    source: 'LiveChatSettingsTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.chat.write',
  }),
  'S-099': row({
    key: 'chat.sound.enabled',
    default: true,
    area: 'chat',
    type: 'boolean',
    meaning: { en: 'Sound on new message (web)', ka: 'ხმოვანი სიგნალი ახალ შეტყობინებაზე (ვები)' },
    source: 'LiveChatSettingsTableSeeder.php, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.chat.write',
  }),
  'S-100': row({
    key: 'notifications.admin_recipients',
    default: ['ir.gvazava@gmail.com'] as string[],
    area: 'notifications',
    type: 'email_list',
    meaning: {
      en: 'Email addresses that receive every admin notification',
      ka: 'ელ-ფოსტის მისამართები, რომლებიც იღებენ ყველა ადმინისტრაციულ შეტყობინებას',
    },
    source: 'Q-026',
    tag: 'NEW',
    critical: true,
    stepUp: true,
    writePermission: 'settings.notifications.write',
  }),
  'S-101': row({
    key: 'notifications.push.enabled',
    default: true,
    area: 'notifications',
    type: 'boolean',
    meaning: { en: 'Mobile push notifications', ka: 'მობილური push შეტყობინებები' },
    source: 'vision, spec 15',
    tag: 'NEW, ACCEPTED P-11',
    public: true,
    writePermission: 'settings.notifications.write',
  }),
  // 4.16 Content, languages, appearance, SEO
  'S-103': row({
    key: 'i18n.default_locale',
    default: 'ka' as 'ka' | 'en',
    area: 'system',
    type: 'enum',
    allowedValues: ['ka', 'en'],
    meaning: {
      en: 'Default language (unprefixed URLs)',
      ka: 'ნაგულისხმევი ენა (URL-ები პრეფიქსის გარეშე)',
    },
    source: 'i18n.md, Q-024',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.system.write',
  }),
  'S-104': row({
    key: 'i18n.language_switcher.enabled',
    default: true,
    area: 'content',
    type: 'boolean',
    meaning: { en: 'Show language switcher', ka: 'ენის გადამრთველის ჩვენება' },
    source: 'settings_general.is_language_switcher, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-105': row({
    key: 'appearance.theme_switcher.enabled',
    default: true,
    area: 'content',
    type: 'boolean',
    meaning: {
      en: 'Users can switch light/dark (web and mobile)',
      ka: 'მომხმარებლებს შეუძლიათ ღია/მუქი თემის გადართვა (ვები და მობილური)',
    },
    source: 'Q-059, settings_appearance.is_theme_switcher',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-106': row({
    key: 'appearance.default_theme',
    default: 'light' as 'light' | 'dark',
    area: 'content',
    type: 'enum',
    allowedValues: ['light', 'dark'],
    meaning: {
      en: 'Theme for users who have not chosen',
      ka: 'თემა მომხმარებლებისთვის, რომლებსაც არ აურჩევიათ',
    },
    source: 'Q-059',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-107': row({
    key: 'appearance.home.featured_categories',
    default: false,
    area: 'content',
    type: 'boolean',
    meaning: {
      en: 'Featured-categories block on home',
      ka: 'რჩეული კატეგორიების ბლოკი მთავარ გვერდზე',
    },
    source: 'settings_appearance, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-108': row({
    key: 'appearance.home.best_sellers',
    default: false,
    area: 'content',
    type: 'boolean',
    meaning: {
      en: 'Best-sellers block on home',
      ka: 'საუკეთესო გამყიდველების ბლოკი მთავარ გვერდზე',
    },
    source: 'settings_appearance, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-109': row({
    // "prod" without a fallback: legacy column default false (Q-068 rule).
    key: 'appearance.home.logo_cloud',
    default: false,
    area: 'content',
    type: 'boolean',
    meaning: { en: 'Logo-cloud block on home', ka: 'ლოგოების ბლოკი მთავარ გვერდზე' },
    source: '2023_09_14_115452_add_enable_logo_cloud_to_settings_appearance_table.php:15, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-111': row({
    // Production values are imported at migration; a new installation starts with the app name
    // (`legacy/APP/config/app.php:18`), the seed separator and no images.
    key: 'branding.site',
    default: {
      siteTitle: 'MyTask',
      siteSubtitle: null,
      titleSeparator: '|',
      logoFileId: null,
      logoDarkFileId: null,
      logoTransparentFileId: null,
      faviconFileId: null,
    } as BrandingStored,
    area: 'content',
    type: 'structured',
    meaning: {
      en: 'Site title, subtitle, title separator, logo, dark logo, transparent logo, favicon',
      ka: 'საიტის სათაური, ქვესათაური, სათაურის გამყოფი, ლოგო, მუქი ლოგო, გამჭვირვალე ლოგო, favicon',
    },
    source: 'settings_general, SettingsGeneralTableSeeder.php',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-112': row({
    key: 'branding.header_announcement',
    default: { text: null, url: null } as AnnouncementStored,
    area: 'content',
    type: 'structured',
    meaning: {
      en: 'Header announcement text + link (ka/en)',
      ka: 'სათაურის განცხადების ტექსტი + ბმული (ka/en)',
    },
    source: 'settings_general, SettingsGeneralTableSeeder.php',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-113': row({
    key: 'content.hero',
    default: { title: null, subtitle: null, imageFileIds: [] } as HeroStored,
    area: 'content',
    type: 'structured',
    meaning: { en: 'Home hero content', ka: 'მთავარი გვერდის ჰერო ბლოკის შინაარსი' },
    source: 'settings_hero, SettingsHeroTableSeeder.php',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-114': row({
    key: 'content.footer',
    default: { links: [], socialLinks: [], logos: [] } as FooterStored,
    area: 'content',
    type: 'structured',
    meaning: {
      en: 'Footer links, social links, footer logos',
      ka: 'ფუტერის ბმულები, სოციალური ქსელების ბმულები, ფუტერის ლოგოები',
    },
    source: 'settings_footer, SettingsFooterTableSeeder.php',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-115': row({
    key: 'seo.defaults',
    default: {
      metaDescription: null,
      keywords: null,
      ogImageFileId: null,
      facebookPageUrl: null,
      facebookAppId: null,
      twitterUsername: null,
    } as SeoDefaultsStored,
    area: 'content',
    type: 'structured',
    meaning: {
      en: 'Default meta description, keywords, OG image, Facebook page/app ID, Twitter username',
      ka: 'ნაგულისხმევი მეტა აღწერა, საკვანძო სიტყვები, OG სურათი, Facebook გვერდი/აპლიკაციის ID, Twitter მომხმარებლის სახელი',
    },
    source: 'settings_seo, SettingsSeoTableSeeder.php',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-116': row({
    key: 'seo.sitemap.enabled',
    default: true,
    area: 'content',
    type: 'boolean',
    meaning: { en: 'Publish /sitemap.xml', ka: '/sitemap.xml-ის გამოქვეყნება' },
    source: 'Q-025, R-042',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-117': row({
    key: 'content.blog.enabled',
    default: true,
    area: 'content',
    type: 'boolean',
    meaning: { en: 'Blog visible', ka: 'ბლოგი ხილულია' },
    source: 'Q-025',
    tag: 'CHANGE',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-118': row({
    key: 'content.blog.comments_enabled',
    default: true,
    area: 'content',
    type: 'boolean',
    meaning: { en: 'Blog comments', ka: 'ბლოგის კომენტარები' },
    source: 'blog_settings, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-119': row({
    // "prod" without a fallback: legacy column default false (Q-068 rule).
    key: 'content.blog.show_on_home',
    default: false,
    area: 'content',
    type: 'boolean',
    meaning: { en: 'Latest posts block on home', ka: 'ბოლო სტატიების ბლოკი მთავარ გვერდზე' },
    source: '2023_10_21_200857_add_display_posts_home_to_blog_settings_table.php:15, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-120': row({
    key: 'content.newsletter.enabled',
    default: true,
    area: 'content',
    type: 'boolean',
    meaning: {
      en: 'Newsletter sign-up (double opt-in)',
      ka: 'სიახლეების გამოწერა (ორმაგი დადასტურებით)',
    },
    source: 'newsletter_settings, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-121': row({
    key: 'system.maintenance_mode',
    default: { enabled: false, headline: null, message: null } as MaintenanceStored,
    area: 'system',
    type: 'structured',
    meaning: {
      en: 'Site in maintenance; admin notified',
      ka: 'საიტი ტექნიკურ სამუშაოებზეა; ადმინისტრატორი ინფორმირებულია',
    },
    source: 'Admin/System/MaintenanceComponent.php',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.system.write',
  }),
  'S-123': row({
    key: 'profile.linked_accounts.enabled',
    default: false,
    area: 'content',
    type: 'boolean',
    meaning: {
      en: 'Linked social profile URLs editor and profile block',
      ka: 'სოციალური პროფილების ბმულების რედაქტორი და პროფილის ბლოკი',
    },
    source: 'P-25, settings_security.is_social_media_accounts, Q-068',
    tag: 'LEGACY',
    public: true,
    writePermission: 'settings.content.write',
  }),
  'S-124': row({
    key: 'auth.two_factor.trigger',
    default: 'new_device' as 'new_device' | 'new_device_or_ip',
    area: 'auth',
    type: 'enum',
    allowedValues: ['new_device', 'new_device_or_ip'],
    meaning: {
      en: 'When a 2FA code is asked: new or expired device only, or also on every new IP',
      ka: 'როდის მოითხოვება კოდი: მხოლოდ ახალ ან ვადაგასულ მოწყობილობაზე, თუ ყოველ ახალ IP-ზეც',
    },
    source: 'Q-082',
    tag: 'NEW',
    stepUp: true,
    writePermission: 'settings.auth.write',
  }),
  'S-126': row({
    key: 'subscriptions.mobile_card_purchase.enabled',
    default: true,
    area: 'subscriptions',
    type: 'boolean',
    meaning: {
      en: 'Premium card purchase inside the mobile apps (points purchase stays)',
      ka: 'Premium-ის ბარათით შეძენა მობილურ აპლიკაციებში (ქულებით შეძენა რჩება)',
    },
    source: 'Q-081, P-60',
    tag: 'NEW',
    public: true,
    writePermission: 'settings.subscriptions.write',
  }),
  'S-130': row({
    key: 'mobile.min_app_version',
    default: { ios: '0.0.0', android: '0.0.0' } as { ios: string; android: string },
    area: 'system',
    type: 'structured',
    meaning: {
      en: 'Lowest mobile app version still served, per platform (older apps must update)',
      ka: 'მობილური აპლიკაციის მინიმალური მხარდაჭერილი ვერსია პლატფორმების მიხედვით (ძველმა ვერსიებმა განახლება უნდა გააკეთონ)',
    },
    source: 'Q-153, ADR-018',
    tag: 'NEW',
    writePermission: 'settings.system.write',
  }),
} as const;

export type SettingId = keyof typeof settingsRegistry;
export const settingIdByKey = new Map(
  Object.entries(settingsRegistry).map(([id, m]) => [m.key, id as SettingId]),
);
