// Generates src/generated/* from the approved contract (ADR-014 §2). Deterministic: same input, same bytes.
// Inputs:  docs/04-api/openapi.yaml (bundle), docs/04-api/src/events/*.yaml (realtime catalogue, realtime.md §4)
// Outputs: src/generated/openapi.ts (paths, components, operations), src/generated/realtime.ts
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { parse } from 'yaml';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const contractPath = join(root, 'docs/04-api/openapi.yaml');
const eventsDir = join(root, 'docs/04-api/src/events');
const outDir = resolve(here, '../src/generated');
mkdirSync(outDir, { recursive: true });

const contractText = readFileSync(contractPath, 'utf8');
const contractHash = createHash('sha256').update(contractText.replace(/\r\n/g, '\n')).digest('hex');
const contract = parse(contractText);
const header = (what) =>
  [
    `// GENERATED by packages/types/scripts/generate.mjs from ${what}. DO NOT EDIT BY HAND.`,
    `// Contract version ${contract.info.version}, sha256 ${contractHash}. Regenerate with \`pnpm gen\`.`,
    '',
  ].join('\n');

// 1. REST types
const ast = await openapiTS(pathToFileURL(contractPath), {
  alphabetize: true,
  exportType: true,
  immutable: false,
  // Contract bodies that are optional must stay optional; `default` values are not "required".
  defaultNonNullable: false,
});
writeFileSync(join(outDir, 'openapi.ts'), header('docs/04-api/openapi.yaml') + astToString(ast));

// 2. Realtime events: event name -> payload schema (the payloads are components of the contract)
const schemaNames = new Set(Object.keys(contract.components?.schemas ?? {}));
// The foundation event is declared in realtime.md (F0 row), not in src/events/*.yaml.
const events = [
  {
    name: 'file.processed',
    payload: 'FileProcessedEvent',
    room: 'user:{ownerUserId} | staff:{staffId}',
    file: 'realtime.md F0',
  },
];
if (!schemaNames.has('FileProcessedEvent'))
  throw new Error('FileProcessedEvent missing from openapi.yaml');
for (const file of readdirSync(eventsDir)
  .filter((f) => f.endsWith('.yaml'))
  .sort()) {
  const doc = parse(readFileSync(join(eventsDir, file), 'utf8'));
  for (const ev of doc?.events ?? []) {
    if (!schemaNames.has(ev.payload)) {
      throw new Error(
        `${file}: event ${ev.name} payload ${ev.payload} is not a schema in openapi.yaml`,
      );
    }
    events.push({ name: ev.name, payload: ev.payload, room: ev.room ?? null, file });
  }
}
events.sort((a, b) => a.name.localeCompare(b.name));
const seen = new Set();
for (const ev of events) {
  if (seen.has(ev.name)) throw new Error(`duplicate realtime event ${ev.name}`);
  seen.add(ev.name);
}
const realtime = [
  header('docs/04-api/src/events/*.yaml (realtime.md)'),
  "import type { components } from './openapi';",
  '',
  '/** Realtime (Socket.IO) event name -> payload type. Envelope: components["schemas"]["RealtimeEnvelope"]. */',
  'export interface RealtimeEvents {',
  ...events.map(
    (ev) =>
      `  /** room \`${ev.room ?? '-'}\` (${ev.file}) */\n  '${ev.name}': components['schemas']['${ev.payload}'];`,
  ),
  '}',
  '',
  'export type RealtimeEventName = keyof RealtimeEvents;',
  '',
  'export const realtimeEventNames = [',
  ...events.map((ev) => `  '${ev.name}',`),
  '] as const satisfies readonly RealtimeEventName[];',
  '',
].join('\n');
writeFileSync(join(outDir, 'realtime.ts'), realtime);

console.log(
  `@mytask/types: ${Object.keys(contract.paths).length} paths, ${schemaNames.size} schemas, ${events.length} realtime events (contract ${contract.info.version})`,
);
